AWSTemplateFormatVersion: 2010-09-09
Description: IO Lab Server & RDS

Parameters:
  appName:
    Description: Application Name
    Type: String
  keypairName:
    Description: bastion key pair name
    Type: String
  bastionInstanceType:
    Description: bastion instance type
    Type: String
  bastionAmiId:
    Description: bastion AMI id
    Type: String
  serverInstanceType:
    Description: server instance type
    Type: String
  serverAmiId:
    Description: server AMI id
    Type: String
  bastionSubnetId:
    Description: bastion subnet id
    Type: String
  bastionSG:
    Description: bastion security group
    Type: String
  serverSubnetId:
    Description: server subnet id
    Type: String
  preprodQualifSG:
    Description: bastion security group
    Type: String
  prodSG:
    Description: bastion security group
    Type: String

Resources:
  bastion:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref keypairName
      ImageId: !Ref bastionAmiId
      InstanceType: !Ref bastionInstanceType
      Monitoring: false
      SubnetId: !Ref bastionSubnetId
      SecurityGroupIds:
      - !Ref bastionSG
      Tags:
      - Key: Name
        Value: !Sub ${appName}-bastion

  eipBastion:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref bastion

  preprodQualif:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref keypairName
      ImageId: !Ref serverAmiId
      InstanceType: !Ref serverInstanceType
      Monitoring: false
      SubnetId: !Ref serverSubnetId
      SecurityGroupIds:
      - !Ref preprodQualifSG
      Tags:
      - Key: Name
        Value: !Sub ${appName}-preprodQualif

  eipPreprodQualif:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref preprodQualif

  prod:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref keypairName
      ImageId: !Ref serverAmiId
      InstanceType: !Ref serverInstanceType
      Monitoring: false
      SubnetId: !Ref serverSubnetId
      SecurityGroupIds:
      - !Ref prodSG
      Tags:
      - Key: Name
        Value: !Sub ${appName}-prod

  eipProd:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref prod