AWSTemplateFormatVersion: 2010-09-09
Description: IO Lab Server & RDS

Parameters:
  appName:
    Description: Application Name
    Type: String
  keypairName:
    Description: bastion key pair name
    Type: String
  bastionInstanceType:
    Description: bastion instance type
    Type: String
  bastionAmiId:
    Description: bastion AMI id
    Type: String
  serverInstanceType:
    Description: server instance type
    Type: String
  serverAmiId:
    Description: server AMI id
    Type: String
  bastionSubnetId:
    Description: bastion subnet id
    Type: String
  bastionSG:
    Description: bastion security group
    Type: String
  serverSubnetId:
    Description: server subnet id
    Type: String
  preprodQualifSG:
    Description: Preprod & Qualif security group
    Type: String
  prodSG:
    Description: Prod security group
    Type: String
  rdsSubnets:
    Description: RDS Subnets
    Type: CommaDelimitedList
  rdsSG:
    Description: RDS security group
    Type: String
  dbAllocatedStorage:
    Description: RDS allocated storage
    Type: Number
  dbInstanceClass:
    Description: RDS instance class
    Type: String
  dbBackupRetentionPeriod:
    Description: RDS backup retention period
    Type: Number
  dbName:
    Description: RDS db name for the first DB
    Type: String
  dbEngine:
    Description: RDS db engine
    Type: String
  dbEngineVersion:
    Description: RDS db engine version
    Type: String
  dbMasterUsername:
    Description: RDS master user name
    Type: String
  dbMasterPassword:
    Description: RDS master password
    Type: String
  dbPort:
    Description: RDS db port
    Type: Number
  dbStorageType:
    Description: RDS storage type
    Type: String

Resources:
  bastion:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref keypairName
      ImageId: !Ref bastionAmiId
      InstanceType: !Ref bastionInstanceType
      Monitoring: false
      SubnetId: !Ref bastionSubnetId
      SecurityGroupIds:
      - !Ref bastionSG
      Tags:
      - Key: Name
        Value: !Sub ${appName}-bastion

  eipBastion:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref bastion

  preprodQualif:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref keypairName
      ImageId: !Ref serverAmiId
      InstanceType: !Ref serverInstanceType
      Monitoring: false
      SubnetId: !Ref serverSubnetId
      SecurityGroupIds:
      - !Ref preprodQualifSG
      Tags:
      - Key: Name
        Value: !Sub ${appName}-preprodQualif

  prod:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref keypairName
      ImageId: !Ref serverAmiId
      InstanceType: !Ref serverInstanceType
      Monitoring: false
      SubnetId: !Ref serverSubnetId
      SecurityGroupIds:
      - !Ref prodSG
      Tags:
      - Key: Name
        Value: !Sub ${appName}-prod

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS Subnet Group
      SubnetIds: !Ref rdsSubnets
      # SubnetIds:
      # - subnet-091df959eebb3b649
      # - subnet-0740f12b8ec630a6c

  rds:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref dbAllocatedStorage
      DBInstanceClass: !Ref dbInstanceClass
      BackupRetentionPeriod: !Ref dbBackupRetentionPeriod
      DBName: !Ref dbName
      DBSubnetGroupName: !Ref RDSSubnetGroup
      Engine: !Ref dbEngine
      EngineVersion: !Ref dbEngineVersion
      MasterUsername: !Ref dbMasterUsername
      MasterUserPassword: !Ref dbMasterPassword
      MultiAZ: false
      Port: !Ref dbPort
      PubliclyAccessible: false
      StorageEncrypted: false
      StorageType: !Ref dbStorageType
      VPCSecurityGroups: 
      - !Ref rdsSG

Outputs:
  OutRdsEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt rds.Endpoint.Address

  OutEipBastion:
    Description: Bastion IP
    Value: !Ref eipBastion

  OutPreproQualifIP:
    Description: Prod IP
    Value: !GetAtt preprodQualif.PrivateIp

  OutProdIP:
    Description: Prod IP
    Value: !GetAtt prod.PrivateIp