AWSTemplateFormatVersion: 2010-09-09
Description: App Migration - App

Parameters:
  TemplateBucket:
    Description: S3 bucket from which nested templates are fetched
    Type: String
  appName:
    Description: App Name
    Type: String
  vpc:
    Description: vpc to work with
    Type: String
  albSG:
    Description: Application Load Balancer
    Type: String
  keypairNameDevPreprod:
    Description: Dev & Preprod key pair name
    Type: String
  keypairNameProd:
    Description: Prod key pair name
    Type: String
  serverInstanceType:
    Description: server instance type
    Type: String
  serverAmiId:
    Description: server AMI id
    Type: String
  dbAllocatedStorage:
    Description: RDS allocated storage
    Type: Number
  dbInstanceClass:
    Description: RDS instance class
    Type: String
  dbBackupRetentionPeriod:
    Description: RDS backup retention period
    Type: Number
  dbEngine:
    Description: RDS db engine
    Type: String
  dbEngineVersion:
    Description: RDS db engine version
    Type: String
  dbMasterUsername:
    Description: RDS master user name
    Type: String
  dbMasterPassword:
    Description: RDS master password
    Type: String
  dbPort:
    Description: RDS db port
    Type: Number
  dbStorageType:
    Description: RDS storage type
    Type: String
  preferredBackupWindow:
    Description: RDS prefered backup window
    Type: String
  preferredMaintenanceWindow:
    Description: RDS prefered maintenance window
    Type: String
  serverSubnetId:
    Description: Server subnet Id
    Type: String
  rdsSubnets:
    Description: RDS subnet Ids
    Type: String
  bastionSG:
    Description: Bastion security group
    Type: String
  devPreprodDomainName:
    Description: Boiron domain name
    Type: String
  prodDomainName:
    Description: Boiron domain name
    Type: String
  HTTPALBListener:
    Description: HTTP ALB listener
    Type: String
  HTTPSALBListener:
    Description: HTTPS ALB listener
    Type: String
  serversAlarmSNS:
    Description: SNS Topic to send email
    Type: String

Resources:
  appNetwork:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-app-network.yaml
      Parameters:
        appName: !Ref appName
        vpc: !Ref vpc
        albSG: !Ref albSG
        dbPort: !Ref dbPort
        bastionSG: !Ref bastionSG
        
  appServer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-app-server.yaml
      Parameters:
        appName: !Ref appName
        keypairNameDevPreprod: !Ref keypairNameDevPreprod
        keypairNameProd: !Ref keypairNameProd
        serverInstanceType: !Ref serverInstanceType
        serverAmiId: !Ref serverAmiId
        serverSubnetId: !Ref serverSubnetId
        devPreprodSG: !GetAtt appNetwork.Outputs.OutDevPreprodSG
        prodSG: !GetAtt appNetwork.Outputs.OutProdSG
        rdsSubnets: !Ref rdsSubnets
        rdsDevPreProdSG: !GetAtt appNetwork.Outputs.OutRDSDevPreProdSG
        rdsProdSG: !GetAtt appNetwork.Outputs.OutRDSProdSG
        dbAllocatedStorage: !Ref dbAllocatedStorage
        dbInstanceClass: !Ref dbInstanceClass
        dbBackupRetentionPeriod: !Ref dbBackupRetentionPeriod
        dbNamePreprod: !Sub ${appName}preprod
        dbNameProd: !Sub ${appName}prod
        dbEngine: !Ref dbEngine
        dbEngineVersion: !Ref dbEngineVersion
        dbMasterUsername: !Ref dbMasterUsername
        dbMasterPassword: !Ref dbMasterPassword
        dbPort: !Ref dbPort
        dbStorageType: !Ref dbStorageType
        preferredBackupWindow: !Ref preferredBackupWindow
        preferredMaintenanceWindow: !Ref preferredMaintenanceWindow
        devPreprodDomainName: !Ref devPreprodDomainName
        prodDomainName:  !Ref prodDomainName
        vpc: !Ref vpc
        HTTPALBListener: !Ref HTTPALBListener
        HTTPSALBListener: !Ref HTTPSALBListener
        serversAlarmSNS: !Ref serversAlarmSNS

Outputs:
  OutRdsDevPreprodEndpoint:
    Description: RDS Dev & Preprod Endpoint
    Value: !GetAtt appServer.Outputs.OutRdsDevPreprodEndpoint

  OutRdsProdEndpoint:
    Description: RDS Dev & Preprod Endpoint
    Value: !GetAtt appServer.Outputs.OutRdsProdEndpoint

  OutDevPreproIP:
    Description: Dev &Preprod private IP
    Value: !GetAtt appServer.Outputs.OutDevPreproIP

  OutProdIP:
    Description: Prod private IP
    Value: !GetAtt appServer.Outputs.OutProdIP


