AWSTemplateFormatVersion: 2010-09-09
Description: IO Lab Server & RDS

Parameters:
  appName:
    Description: Application Name
    Type: String
  keypairName:
    Description: bastion key pair name
    Type: String
  serverInstanceType:
    Description: server instance type
    Type: String
  serverAmiId:
    Description: server AMI id
    Type: String
  serverSubnetId:
    Description: server subnet id
    Type: String
  preprodQualifSG:
    Description: Preprod & Qualif security group
    Type: String
  prodSG:
    Description: Prod security group
    Type: String
  rdsSubnets:
    Description: RDS Subnets
    Type: CommaDelimitedList
  rdsSG:
    Description: RDS security group
    Type: String
  dbAllocatedStorage:
    Description: RDS allocated storage
    Type: Number
  dbInstanceClass:
    Description: RDS instance class
    Type: String
  dbBackupRetentionPeriod:
    Description: RDS backup retention period
    Type: Number
  dbName:
    Description: RDS db name for the first DB
    Type: String
  dbEngine:
    Description: RDS db engine
    Type: String
  dbEngineVersion:
    Description: RDS db engine version
    Type: String
  dbMasterUsername:
    Description: RDS master user name
    Type: String
  dbMasterPassword:
    Description: RDS master password
    Type: String
  dbPort:
    Description: RDS db port
    Type: Number
  dbStorageType:
    Description: RDS storage type
    Type: String
  preferredBackupWindow:
    Description: RDS prefered backup window
    Type: String
  preferredMaintenanceWindow:
    Description: RDS prefered maintenance window
    Type: String
  iolabDomainName:
    Description: Boiron domain name
    Type: String
  appDomainName:
    Description: Boiron domain name
    Type: String
  vpc:
    Description: VPC
    Type: String
  HTTPALBListener:
    Description: HTTP ALB listener
    Type: String
  HTTPSALBListener:
    Description: HTTPS ALB listener
    Type: String

Resources:
  # bastion:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     KeyName: !Ref keypairName
  #     ImageId: !Ref bastionAmiId
  #     InstanceType: !Ref bastionInstanceType
  #     Monitoring: false
  #     SubnetId: !Ref bastionSubnetId
  #     SecurityGroupIds:
  #     - !Ref bastionSG
  #     Tags:
  #     - Key: Name
  #       Value: !Sub ${appName}-bastion

  # eipBastion:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: vpc
  #     InstanceId: !Ref bastion

  preprodQualif:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref keypairName
      ImageId: !Ref serverAmiId
      InstanceType: !Ref serverInstanceType
      Monitoring: false
      SubnetId: !Ref serverSubnetId
      SecurityGroupIds:
      - !Ref preprodQualifSG
      Tags:
      - Key: Name
        Value: !Sub ${appName}-preprodQualif
      - Key: SCHEDULING
        Value: Standard

  prod:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref keypairName
      ImageId: !Ref serverAmiId
      InstanceType: !Ref serverInstanceType
      Monitoring: false
      SubnetId: !Ref serverSubnetId
      SecurityGroupIds:
      - !Ref prodSG
      Tags:
      - Key: Name
        Value: !Sub ${appName}-prod

  # serversAlarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     ActionsEnabled: true
  #     AlarmActions:
  #       - !Ref serversAlarmSNS
  #     AlarmDescription: Alarm when instance not responding
  #     AlarmName: boironInstanceCheck
  #     ComparisonOperator: GreaterThanOrEqualToThreshold
  #     Dimensions:
  #     - Name: InstanceId
  #       Value: !Ref prod
  #     EvaluationPeriods: 1
  #     MetricName: StatusCheckFailed_Instance
  #     Namespace: AWS/EC2
  #     Period: 300
  #     Statistic: SampleCount
  #     Threshold: 1.0
  #     TreatMissingData: missing

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS Subnet Group
      SubnetIds: !Ref rdsSubnets
      # SubnetIds:
      # - subnet-02afb78c27a119988
      # - subnet-0392ef04f8f6f7173

  rds:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref dbAllocatedStorage
      DBInstanceClass: !Ref dbInstanceClass
      BackupRetentionPeriod: !Ref dbBackupRetentionPeriod
      DBName: !Ref dbName
      DBSubnetGroupName: !Ref RDSSubnetGroup
      Engine: !Ref dbEngine
      EngineVersion: !Ref dbEngineVersion
      MasterUsername: !Ref dbMasterUsername
      MasterUserPassword: !Ref dbMasterPassword
      MultiAZ: false
      Port: !Ref dbPort
      PubliclyAccessible: false
      StorageEncrypted: false
      StorageType: !Ref dbStorageType
      VPCSecurityGroups: 
      - !Ref rdsSG
      PreferredBackupWindow: !Ref preferredBackupWindow
      PreferredMaintenanceWindow: !Ref preferredMaintenanceWindow

  HTTPALBRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HTTPALBListener
      Priority: 1
      Conditions:
        -
          Field: host-header
          Values: 
          - !Sub ${appDomainName}.${iolabDomainName}
      Actions:
        -
          Type: forward
          TargetGroupArn: !Ref HTTPTarget
  
  HTTPSALBRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HTTPSALBListener
      Priority: 1
      Conditions:
        -
          Field: host-header
          Values: 
          - !Sub ${appDomainName}.${iolabDomainName}
      Actions:
        -
          Type: forward
          TargetGroupArn: !Ref HTTPSTarget

  HTTPTarget:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref vpc
      TargetType: instance
      Port: 80
      Protocol: HTTP
      Name: !Sub ${appName}-HTTPTarget
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 20
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      # Targets:
      #   AvailabilityZone: String
      #   Id: String
    # DependsOn: ALB

  HTTPSTarget:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref vpc
      TargetType: instance
      Port: 443
      Protocol: HTTPS
      Name: !Sub ${appName}-HTTPSTarget
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 20
      HealthCheckPath: /
      HealthCheckProtocol: HTTPS
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      # Targets:
      # - Id: i-00513634c46216980
    # DependsOn: ALB

Outputs:
  OutRdsEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt rds.Endpoint.Address

  OutPreproQualifIP:
    Description: Prod IP
    Value: !GetAtt preprodQualif.PrivateIp

  OutProdIP:
    Description: Prod IP
    Value: !GetAtt prod.PrivateIp