AWSTemplateFormatVersion: 2010-09-09
Description: IO LAB Root stack

Parameters:
  TemplateBucket:
    Description: S3 bucket from which nested templates are fetched
    Type: String
  KeyPairName:
    Description: EC2 key pair name
    Type: String
  bastionInstanceType:
    Description: Bastion instance type
    Type: String
  bastionAmiId:
    Description: Bastion ami ID
    Type: String
    Default: ami-059eeca93cf09eebd
  serverInstanceType:
    Description: Server instance type
    Type: String
  serverAmiId:
    Description: Server ami ID
    Type: String
    Default: ami-059eeca93cf09eebd
  dbAllocatedStorage:
    Description: RDS allocated storage
    Type: Number
    Default: 10
  dbInstanceClass:
    Description: RDS instance class
    Type: String
    Default: db.t2.micro
  dbBackupRetentionPeriod:
    Description: RDS backup retention period
    Type: Number
    Default: 7
  dbName:
    Description: RDS db name for the first DB
    Type: String
    Default: app
  dbEngine:
    Description: RDS db engine
    Type: String
    Default: mysql
  dbMasterUsername:
    Description: RDS master user name
    Type: String
    Default: master
  dbMasterPassword:
    Description: RDS master password
    Type: String
  dbPort:
    Description: RDS db port
    Type: Number
    Default: 3306
  dbStorageType:
    Description: RDS storage type
    Type: String
    Default: gp2
  preferredBackupWindow:
    Description: RDS prefered backup window
    Type: String
    Default: 00:00-00:30
  preferredMaintenanceWindow:
    Description: RDS prefered maintenance window
    Type: String
    Default: Sun:00:30-Sun:01:00
  BucketName:
    Description: Bucket name to store related files of the project
    Type: String
    Default: behlers-test1

Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-vpc.yaml
      Parameters:
        ProjectName: IOLAB
        bastionSourceIp: 0.0.0.0/0
        keypairName: !Ref KeyPairName
        bastionInstanceType: !Ref bastionInstanceType
        bastionAmiId: !Ref bastionAmiId
        dbPort: !Ref dbPort

  lambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-lambda.yaml
      Parameters:
        TemplateBucket: !Ref TemplateBucket

  boiron:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-app.yaml
      Parameters:
        TemplateBucket: !Ref TemplateBucket
        appName: boiron
        vpc: !GetAtt vpc.Outputs.IOLABVPC
        albSG: !GetAtt vpc.Outputs.ALBSG
        keypairName: !Ref KeyPairName
        serverInstanceType: !Ref serverInstanceType
        serverAmiId: !Ref serverAmiId
        dbAllocatedStorage: !Ref dbAllocatedStorage
        dbInstanceClass: !Ref dbInstanceClass
        dbBackupRetentionPeriod: !Ref dbBackupRetentionPeriod
        dbName: !Ref dbName
        dbEngine: mysql
        dbEngineVersion: 5.7.23
        dbMasterUsername: !Ref dbMasterUsername
        dbMasterPassword: !Ref dbMasterPassword
        dbPort: !Ref dbPort
        dbStorageType: !Ref dbStorageType
        preferredBackupWindow: !Ref preferredBackupWindow
        preferredMaintenanceWindow: !Ref preferredMaintenanceWindow
        serverSubnetId: !GetAtt vpc.Outputs.OutSubnetPrivateA
        rdsSubnets: 
          Fn::Join:
            - ','
            - -  !GetAtt vpc.Outputs.OutSubnetPrivateA
              -  !GetAtt vpc.Outputs.OutSubnetPrivateB
        bastionSG: !GetAtt vpc.Outputs.OutBastionSG

  # Vicat:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-app.yaml
  #     Parameters:
  #       TemplateBucket: !Ref TemplateBucket
  #       appName: vicat
  #       vpc: !GetAtt vpc.Outputs.IOLABVPC
  #       albSG: !GetAtt vpc.Outputs.ALBSG
  #       routeTablePublic: !GetAtt vpc.Outputs.IOLABRouteTablePublic
  #       classCSubnetPrivateA: 4
  #       classCSubnetPrivateB: 5
  #       classCSubnetPublicA: 6
  #       bastionSourceIp: 0.0.0.0/0
  #       keypairName: !Ref KeyPairName
  #       bastionInstanceType: !Ref bastionInstanceType
  #       bastionAmiId: !Ref bastionAmiId
  #       serverInstanceType: !Ref serverInstanceType
  #       serverAmiId: !Ref serverAmiId
  #       dbAllocatedStorage: !Ref dbAllocatedStorage
  #       dbInstanceClass: !Ref dbInstanceClass
  #       dbBackupRetentionPeriod: !Ref dbBackupRetentionPeriod
  #       dbName: !Ref dbName
  #       dbEngine: mysql
  #       dbEngineVersion: 5.7.23
  #       dbMasterUsername: !Ref dbMasterUsername
  #       dbMasterPassword: !Ref dbMasterPassword
  #       dbPort: !Ref dbPort
  #       dbStorageType: !Ref dbStorageType
  #      preferredBackupWindow: !Ref preferredBackupWindow
  #      preferredMaintenanceWindow: !Ref preferredMaintenanceWindow

  # Mutual:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-app.yaml
  #     Parameters:
  #       TemplateBucket: !Ref TemplateBucket
  #       appName: mutual
  #       vpc: !GetAtt vpc.Outputs.IOLABVPC
  #       albSG: !GetAtt vpc.Outputs.ALBSG
  #       routeTablePublic: !GetAtt vpc.Outputs.IOLABRouteTablePublic
  #       classCSubnetPrivateA: 8
  #       classCSubnetPrivateB: 9
  #       classCSubnetPublicA: 10
  #       bastionSourceIp: 0.0.0.0/0
  #       keypairName: !Ref KeyPairName
  #       bastionInstanceType: !Ref bastionInstanceType
  #       bastionAmiId: !Ref bastionAmiId
  #       serverInstanceType: !Ref serverInstanceType
  #       serverAmiId: !Ref serverAmiId
  #       dbAllocatedStorage: !Ref dbAllocatedStorage
  #       dbInstanceClass: !Ref dbInstanceClass
  #       dbBackupRetentionPeriod: !Ref dbBackupRetentionPeriod
  #       dbName: !Ref dbName
  #       dbEngine: mysql
  #       dbEngineVersion: 5.7.23
  #       dbMasterUsername: !Ref dbMasterUsername
  #       dbMasterPassword: !Ref dbMasterPassword
  #       dbPort: !Ref dbPort
  #       dbStorageType: !Ref dbStorageType
  #       preferredBackupWindow: !Ref preferredBackupWindow
  #       preferredMaintenanceWindow: !Ref preferredMaintenanceWindow

  # global:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-global.yaml
  #     Parameters:
  #       ProjectName: IOLAB
  #       albSG: !GetAtt vpc.Outputs.ALBSG
  #       ALBSubnets:  
  #         Fn::Join:
  #           - ','
  #           - -  !GetAtt vpc.Outputs.OutSubnetPublicA
  #             -  !GetAtt vpc.Outputs.OutSubnetPublicB
  #       vpc: !GetAtt vpc.Outputs.IOLABVPC
  #       BucketName: !Ref BucketName

Outputs:
  # GLOBAL OUTPUTS
  EipBastion:
    Description: Bastion EIP
    Value: !GetAtt vpc.Outputs.OutBastionEIP

  # BOIRON OUTPUTS
  BoironRdsEndpoint:
    Description: Boiron RDS Endpoint
    Value: !GetAtt boiron.Outputs.OutRdsEndpoint

  BoironPreproQualifIP:
    Description: Boiron preprod & qualif private IP
    Value: !GetAtt boiron.Outputs.OutPreproQualifIP

  BoironProdIP:
    Description: Boiron Prod private IP
    Value: !GetAtt boiron.Outputs.OutProdIP

  # VICAT OUTPUTS
  # VicatRdsEndpoint:
  #   Description: Vicat RDS Endpoint
  #   Value: !GetAtt Vicat.Outputs.OutRdsEndpoint

  # VicatEipBastion:
  #   Description: Vicat Bastion IP
  #   Value: !GetAtt Vicat.Outputs.OutEipBastion

  # VicatPreproQualifIP:
  #   Description: Vicat preprod & qualif private IP
  #   Value: !GetAtt Vicat.Outputs.OutPreproQualifIP

  # VicatProdIP:
  #   Description: Vicat Prod private IP
  #   Value: !GetAtt Vicat.Outputs.OutProdIP

  # MUTUAL OUTPUTS
  # MutualRdsEndpoint:
  #   Description: Mutual RDS Endpoint
  #   Value: !GetAtt Mutual.Outputs.OutRdsEndpoint

  # MutualEipBastion:
  #   Description: Mutual Bastion IP
  #   Value: !GetAtt Mutual.Outputs.OutEipBastion

  # MutualPreproQualifIP:
  #   Description: Mutual preprod & qualif private IP
  #   Value: !GetAtt Mutual.Outputs.OutPreproQualifIP

  # MutualProdIP:
  #   Description: Mutual Prod private IP
  #   Value: !GetAtt Mutual.Outputs.OutProdIP