AWSTemplateFormatVersion: 2010-09-09
Description: IO LAB Root stack

Parameters:
  TemplateBucket:
    Description: S3 bucket from which nested templates are fetched
    Type: String
  KeyPairName:
    Description: EC2 key pair name
    Type: String
  bastionInstanceType:
    Description: Bastion instance type
    Type: String
  bastionAmiId:
    Description: Bastion ami ID
    Type: String
    Default: ami-059eeca93cf09eebd
  serverInstanceType:
    Description: Server instance type
    Type: String
  serverAmiId:
    Description: Server ami ID
    Type: String
    Default: ami-059eeca93cf09eebd

Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-vpc.yaml

  boiron:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-app.yaml
      Parameters:
        TemplateBucket: !Ref TemplateBucket
        vpc: !GetAtt vpc.Outputs.IOLABVPC
        albSG: !GetAtt vpc.Outputs.ALBSG
        routeTablePublic: !GetAtt vpc.Outputs.IOLABRouteTablePublic
        classCSubnetPrivateA: 0
        classCSubnetPrivateB: 1
        classCSubnetPublicA: 2
        bastionSourceIp: 0.0.0.0/0
        keypairName: !Ref KeyPairName
        bastionInstanceType: !Ref bastionInstanceType
        bastionAmiId: !Ref bastionAmiId
        serverInstanceType: !Ref serverInstanceType
        serverAmiId: !Ref serverAmiId