AWSTemplateFormatVersion: 2010-09-09
Description: IO Lab App

Parameters:
  TemplateBucket:
    Description: S3 bucket from which nested templates are fetched
    Type: String
  appName:
    Description: App Name
    Type: String
  vpc:
    Description: vpc to work with
    Type: String
  albSG:
    Description: Application Load Balancer
    Type: String
  keypairName:
    Description: key pair name
    Type: String
  serverInstanceType:
    Description: server instance type
    Type: String
  serverAmiId:
    Description: server AMI id
    Type: String
  dbAllocatedStorage:
    Description: RDS allocated storage
    Type: Number
  dbInstanceClass:
    Description: RDS instance class
    Type: String
  dbBackupRetentionPeriod:
    Description: RDS backup retention period
    Type: Number
  dbName:
    Description: RDS db name for the first DB
    Type: String
  dbEngine:
    Description: RDS db engine
    Type: String
  dbEngineVersion:
    Description: RDS db engine version
    Type: String
  dbMasterUsername:
    Description: RDS master user name
    Type: String
  dbMasterPassword:
    Description: RDS master password
    Type: String
  dbPort:
    Description: RDS db port
    Type: Number
  dbStorageType:
    Description: RDS storage type
    Type: String
  preferredBackupWindow:
    Description: RDS prefered backup window
    Type: String
  preferredMaintenanceWindow:
    Description: RDS prefered maintenance window
    Type: String
  serverSubnetId:
    Description: Server subnet Id
    Type: String
  rdsSubnets:
    Description: RDS subnet Ids
    Type: String
  bastionSG:
    Description: Bastion security group
    Type: String
  iolabDomainName:
    Description: Boiron domain name
    Type: String
  appDomainName:
    Description: Boiron domain name
    Type: String
  HTTPALBListener:
    Description: HTTP ALB listener
    Type: String
  HTTPSALBListener:
    Description: HTTPS ALB listener
    Type: String

Resources:
  appNetwork:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-network.yaml
      Parameters:
        appName: !Ref appName
        vpc: !Ref vpc
        albSG: !Ref albSG
        dbPort: !Ref dbPort
        bastionSG: !Ref bastionSG
        
  appServer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-server.yaml
      Parameters:
        appName: !Ref appName
        keypairName: !Ref keypairName
        serverInstanceType: !Ref serverInstanceType
        serverAmiId: !Ref serverAmiId
        serverSubnetId: !Ref serverSubnetId
        preprodQualifSG: !GetAtt appNetwork.Outputs.OutPreprodQualifSG
        prodSG: !GetAtt appNetwork.Outputs.OutProdSG
        rdsSubnets: !Ref rdsSubnets
        rdsSG: !GetAtt appNetwork.Outputs.OutRDSSG
        dbAllocatedStorage: !Ref dbAllocatedStorage
        dbInstanceClass: !Ref dbInstanceClass
        dbBackupRetentionPeriod: !Ref dbBackupRetentionPeriod
        dbName: !Ref dbName
        dbEngine: !Ref dbEngine
        dbEngineVersion: !Ref dbEngineVersion
        dbMasterUsername: !Ref dbMasterUsername
        dbMasterPassword: !Ref dbMasterPassword
        dbPort: !Ref dbPort
        dbStorageType: !Ref dbStorageType
        preferredBackupWindow: !Ref preferredBackupWindow
        preferredMaintenanceWindow: !Ref preferredMaintenanceWindow
        iolabDomainName: !Ref iolabDomainName
        appDomainName:  !Ref appDomainName
        vpc: !Ref vpc
        HTTPALBListener: !Ref HTTPALBListener
        HTTPSALBListener: !Ref HTTPSALBListener

Outputs:
  OutRdsEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt appServer.Outputs.OutRdsEndpoint

  OutPreproQualifIP:
    Description: Preprod & Qualif private IP
    Value: !GetAtt appServer.Outputs.OutPreproQualifIP

  OutProdIP:
    Description: Prod private IP
    Value: !GetAtt appServer.Outputs.OutProdIP


