AWSTemplateFormatVersion: 2010-09-09
Description: App Migration - Root stack

Parameters:
  TemplateBucket:
    Description: S3 bucket from which nested templates are fetched
    Type: String
  ProjectName:
    Description: Project name used for naming and tagging
    Type: String
  BastionKeyPairName:
    Description: EC2 key pair name
    Type: String
    Default: app-migration-bastion
  bastionInstanceType:
    Description: Bastion instance type
    Type: String
    Default: t2.micro
  bastionAmiId:
    Description: Bastion ami ID
    Type: String
    Default: ami-0fad8cb11d5e5a502 # amazon image with CLI (eu-west-3)
  serverInstanceType:
    Description: Server instance type
    Type: String
    Default: t3.medium
  serverAmiId:
    Description: Server ami ID
    Type: String
    Default: ami-075b44448d2276521 # Ubuntu 16.04 (eu-west-3)
  dbAllocatedStorage:
    Description: RDS allocated storage
    Type: Number
    Default: 10
  dbInstanceClass:
    Description: RDS instance class
    Type: String
    Default: db.t2.medium
  dbBackupRetentionPeriod:
    Description: RDS backup retention period
    Type: Number
    Default: 7
  dbEngine:
    Description: RDS db engine
    Type: String
    Default: mysql
  dbEngineVersion:
    Description: RDS db engine version
    Type: String
    Default: 5.7.23
  dbMasterUsername:
    Description: RDS master user name
    Type: String
    Default: master
  dbMasterPassword:
    Description: RDS master password
    Type: String
    Default: master1234
  dbPort:
    Description: RDS db port
    Type: Number
    Default: 3306
  dbStorageType:
    Description: RDS storage type
    Type: String
    Default: gp2
  preferredBackupWindow:
    Description: RDS prefered backup window
    Type: String
    Default: 02:00-02:30
  preferredMaintenanceWindow:
    Description: RDS prefered maintenance window
    Type: String
    Default: Sun:02:30-Sun:03:00
  BucketName:
    Description: Bucket name to store related files of the project
    Type: String
    Default: app-migration
  iolabDomainName:
    Description: IO-Lab domain name
    Type: String
    Default: cloud.hardisaws.com

Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-vpc-global.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        BucketName: !Ref BucketName
        bastionSourceIp: 0.0.0.0/0 # TODO: 178.18.54.246
        BastionKeyPairName: !Ref BastionKeyPairName
        bastionInstanceType: !Ref bastionInstanceType
        bastionAmiId: !Ref bastionAmiId
        dbPort: !Ref dbPort

  vicat:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-app.yaml
      Parameters:
        TemplateBucket: !Ref TemplateBucket
        appName: vicat
        vpc: !GetAtt vpc.Outputs.IOLABVPC
        albSG: !GetAtt vpc.Outputs.ALBSG
        keypairNameDevPreprod: vicat-dev-preprod
        keypairNameProd: vicat-prod
        serverInstanceType: !Ref serverInstanceType
        serverAmiId: !Ref serverAmiId
        dbAllocatedStorage: !Ref dbAllocatedStorage
        dbInstanceClass: !Ref dbInstanceClass
        dbBackupRetentionPeriod: !Ref dbBackupRetentionPeriod
        dbEngine: !Ref dbEngine
        dbEngineVersion: !Ref dbEngineVersion
        dbMasterUsername: !Ref dbMasterUsername
        dbMasterPassword: !Ref dbMasterPassword
        dbPort: !Ref dbPort
        dbStorageType: !Ref dbStorageType
        preferredBackupWindow: !Ref preferredBackupWindow
        preferredMaintenanceWindow: !Ref preferredMaintenanceWindow
        serverSubnetId: !GetAtt vpc.Outputs.OutSubnetPrivateA
        rdsSubnets: 
          Fn::Join:
            - ','
            - -  !GetAtt vpc.Outputs.OutSubnetPrivateA
              -  !GetAtt vpc.Outputs.OutSubnetPrivateB
        bastionSG: !GetAtt vpc.Outputs.OutBastionSG
        devPreprodDomainName: devpreprodvicat.iolab.fr # TODO: to be updated
        prodDomainName:  prod.vicat.fr # TODO: to be updated
        HTTPALBListener: !GetAtt vpc.Outputs.OutHTTPALBListener
        HTTPSALBListener: !GetAtt vpc.Outputs.OutHTTPSALBListener
        serversAlarmSNS: !GetAtt vpc.Outputs.OutServersAlarmSNS
        albDnsName: vpc.Outputs.OutAlbDnsName
        BucketName: !Ref BucketName

Outputs:
  # GLOBAL OUTPUTS
  EipBastion:
    Description: Bastion EIP
    Value: !GetAtt vpc.Outputs.OutBastionEIP

  # VICAT OUTPUTS
  VicatRdsDevPreprodEndpoint:
    Description: vicat RDS Dev & Preprod Endpoint
    Value: !GetAtt vicat.Outputs.OutRdsDevPreprodEndpoint

  VicatRdsProdEndpoint:
    Description: vicat RDS prod Endpoint
    Value: !GetAtt vicat.Outputs.OutRdsProdEndpoint

  VicatDevPreprodIP:
    Description: vicat dev & preprod private IP
    Value: !GetAtt vicat.Outputs.OutDevPreproIP

  VicatProdIP:
    Description: vicat Prod private IP
    Value: !GetAtt vicat.Outputs.OutProdIP

  VicatCloudfrontDistribution:
    Description: Vicat CloudFrontDistribution Domain Name
    Value: !GetAtt vicat.Outputs.OutCloudfrontDistribution