AWSTemplateFormatVersion: 2010-09-09
Description: IO LAB Root stack

Parameters:
  TemplateBucket:
    Description: S3 bucket from which nested templates are fetched
    Type: String
  ProjectName:
    Description: Project name used for naming and tagging
    Type: String
  BastionKeyPairName:
    Description: EC2 key pair name
    Type: String
    Default: app-migration-bastion
  bastionInstanceType:
    Description: Bastion instance type
    Type: String
    Default: t2.micro
  bastionAmiId:
    Description: Bastion ami ID
    Type: String
    Default: ami-0fad8cb11d5e5a502
  serverInstanceType:
    Description: Server instance type
    Type: String
    Default: t3.medium
  serverAmiId:
    Description: Server ami ID
    Type: String
    Default: ami-28fd4c55
  dbAllocatedStorage:
    Description: RDS allocated storage
    Type: Number
    Default: 10
  dbInstanceClass:
    Description: RDS instance class
    Type: String
    Default: db.t2.medium
  dbBackupRetentionPeriod:
    Description: RDS backup retention period
    Type: Number
    Default: 7
  dbName:
    Description: RDS db name for the first DB
    Type: String
    Default: app
  dbEngine:
    Description: RDS db engine
    Type: String
    Default: mysql
  dbMasterUsername:
    Description: RDS master user name
    Type: String
    Default: master
  dbMasterPassword:
    Description: RDS master password
    Type: String
    Default: master1234
  dbPort:
    Description: RDS db port
    Type: Number
    Default: 3306
  dbStorageType:
    Description: RDS storage type
    Type: String
    Default: gp2
  preferredBackupWindow:
    Description: RDS prefered backup window
    Type: String
    Default: 02:00-02:30
  preferredMaintenanceWindow:
    Description: RDS prefered maintenance window
    Type: String
    Default: Sun:02:30-Sun:03:00
  BucketName:
    Description: Bucket name to store related files of the project
    Type: String
    Default: app-migration
  iolabDomainName:
    Description: IO-Lab domain name
    Type: String
    Default: cloud.hardisaws.com

Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-vpc-global.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        BucketName: !Ref BucketName
        bastionSourceIp: 0.0.0.0/0
        keypairName: !Ref BastionKeyPairName
        bastionInstanceType: !Ref bastionInstanceType
        bastionAmiId: !Ref bastionAmiId
        dbPort: !Ref dbPort

  # global:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-global.yaml
  #     Parameters:
  #       ProjectName: IOLAB
  #       albSG: !GetAtt vpc.Outputs.ALBSG
  #       ALBSubnets:  
  #         Fn::Join:
  #           - ','
  #           - -  !GetAtt vpc.Outputs.OutSubnetPublicA
  #             -  !GetAtt vpc.Outputs.OutSubnetPublicB
  #       vpc: !GetAtt vpc.Outputs.IOLABVPC
  #       BucketName: !Ref BucketName

  Vicat:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/stack/iolab-app.yaml
      Parameters:
        TemplateBucket: !Ref TemplateBucket
        appName: vicat
        vpc: !GetAtt vpc.Outputs.IOLABVPC
        albSG: !GetAtt vpc.Outputs.ALBSG
        keypairName: !Ref BastionKeyPairName
        serverInstanceType: !Ref serverInstanceType
        serverAmiId: !Ref serverAmiId
        dbAllocatedStorage: !Ref dbAllocatedStorage
        dbInstanceClass: !Ref dbInstanceClass
        dbBackupRetentionPeriod: !Ref dbBackupRetentionPeriod
        dbName: !Ref dbName
        dbEngine: mysql
        dbEngineVersion: 5.7.23
        dbMasterUsername: !Ref dbMasterUsername
        dbMasterPassword: !Ref dbMasterPassword
        dbPort: !Ref dbPort
        dbStorageType: !Ref dbStorageType
        preferredBackupWindow: !Ref preferredBackupWindow
        preferredMaintenanceWindow: !Ref preferredMaintenanceWindow
        serverSubnetId: !GetAtt vpc.Outputs.OutSubnetPrivateA
        rdsSubnets: 
          Fn::Join:
            - ','
            - -  !GetAtt vpc.Outputs.OutSubnetPrivateA
              -  !GetAtt vpc.Outputs.OutSubnetPrivateB
        bastionSG: !GetAtt vpc.Outputs.OutBastionSG
        iolabDomainName: !Ref iolabDomainName
        appDomainName:  boiron
        HTTPALBListener: !GetAtt vpc.Outputs.OutHTTPALBListener
        # HTTPSALBListener: !GetAtt vpc.Outputs.OutHTTPSALBListener

Outputs:
  # GLOBAL OUTPUTS
  EipBastion:
    Description: Bastion EIP
    Value: !GetAtt vpc.Outputs.OutBastionEIP

  # VICAT OUTPUTS
  # VicatRdsEndpoint:
  #   Description: Vicat RDS Endpoint
  #   Value: !GetAtt Vicat.Outputs.OutRdsEndpoint

  # VicatEipBastion:
  #   Description: Vicat Bastion IP
  #   Value: !GetAtt Vicat.Outputs.OutEipBastion

  # VicatPreproQualifIP:
  #   Description: Vicat preprod & qualif private IP
  #   Value: !GetAtt Vicat.Outputs.OutPreproQualifIP

  # VicatProdIP:
  #   Description: Vicat Prod private IP
  #   Value: !GetAtt Vicat.Outputs.OutProdIP

  # MUTUAL OUTPUTS
  # MutualRdsEndpoint:
  #   Description: Mutual RDS Endpoint
  #   Value: !GetAtt Mutual.Outputs.OutRdsEndpoint

  # MutualEipBastion:
  #   Description: Mutual Bastion IP
  #   Value: !GetAtt Mutual.Outputs.OutEipBastion

  # MutualPreproQualifIP:
  #   Description: Mutual preprod & qualif private IP
  #   Value: !GetAtt Mutual.Outputs.OutPreproQualifIP

  # MutualProdIP:
  #   Description: Mutual Prod private IP
  #   Value: !GetAtt Mutual.Outputs.OutProdIP