AWSTemplateFormatVersion: 2010-09-09
Description: IO Lab ALB

Parameters:
  ProjectName:
    Description: project name
    Type: String
  albSG:
    Description: Application Laod Balancer security group
    Type: String
  ALBSubnets:
    Description: bastion instance type
    Type: CommaDelimitedList
  vpc:
    Description: vpc
    Type: String
  BucketName:
    Description: Bucket name
    Type: String
  iolabCertificate:
    Description: IO-Lab certificate
    Type: String
    Default: arn:aws:acm:us-east-1:315777477680:certificate/3fe79bb2-ca50-4931-9c72-c6d67c9ab1ce

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      Name: !Sub ${ProjectName}-ALB
      SecurityGroups:
        - !Ref albSG
      Subnets: !Ref ALBSubnets
      Tags:
      - Key: Name
        Value: !Sub ${ProjectName}-ALB

  HTTPALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      DefaultActions:
        -
          Type: fixed-response
          FixedResponseConfig:
            ContentType: text/plain
            MessageBody: Forbidden
            StatusCode: 403
      Port: 80
      Protocol: HTTP

  HTTPSALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      DefaultActions:
        -
          Type: fixed-response
          FixedResponseConfig:
            ContentType: text/plain
            MessageBody: Forbidden
            StatusCode: 403
      Port: 443
      Protocol: HTTPS
      Certificates: 
      - CertificateArn: !Ref iolabCertificate

  # cloudfrontDistribution:
  #   Type: AWS::CloudFront::Distribution
  #   Properties:
  #     DistributionConfig:
  #       Origins:
  #         - DomainName: !GetAtt ALB.DNSName
  #           Id: albOrigin
  #           CustomOriginConfig:
  #             OriginProtocolPolicy: match-viewer
  #       DefaultCacheBehavior: 
  #         AllowedMethods:
  #         - DELETE
  #         - GET
  #         - HEAD
  #         - OPTIONS
  #         - PATCH
  #         - POST
  #         - PUT
  #         TargetOriginId: albOrigin
  #         ForwardedValues:
  #           QueryString: true
  #           Cookies:
  #             Forward: none
  #         ViewerProtocolPolicy: redirect-to-https
  #       DefaultRootObject: index.html
  #       Enabled: true
  #       Logging:
  #         IncludeCookies: true
  #         Bucket: !Sub ${BucketName}.s3.amazonaws.com
  #         Prefix: CloudfrontLogs
  #       ViewerCertificate:
  #         AcmCertificateArn: !Ref iolabCertificate
  #         SslSupportMethod: sni-only

  # iolabHostedZone:
  #   Type: AWS::Route53::HostedZone
  #   Properties:
  #     Name: !Sub ${vygonDomainName}

  # boironRecordSet:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     Name: !Sub ${boironDomainName}.${iolabDomainName}.
  #     Type: A
  #     AliasTarget: 
  #       DNSName: !GetAtt cloudfrontDistribution.DomainName
  #       EvaluateTargetHealth: false
  #       HostedZoneId: Z2FDTNDATAQYW2
  #     HostedZoneId: Z8RQBL38LYV52 # To be replaced by hosted zone Id if created whitin the stack --> !Ref route53HostedZone

Outputs:
  OutHTTPALBListener:
    Description: HTTP ALB Listener
    Value: !Ref HTTPALBListener

  OutHTTPSALBListener:
    Description: HTTPS ALB Listener
    Value: !Ref HTTPSALBListener